apiVersion: v1
kind: Service
metadata:
  name: {{ template "roar-db.name" . }}
  labels:
    app: {{ template "roar-db.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.service.frontendPortName }}
    port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.externalPort }}
  selector:
    app: {{ template "roar-db.name" . }}
     

